[INFOS]
version=%VERSION%
md5=%VERSION_MD5%


[INSERT]
<!-- BEGIN_BLOCK INSERT -->
%FILE_MD5%	%FILE%
<!-- END_BLOCK INSERT -->

[UPDATE]
<!-- BEGIN_BLOCK UPDATE -->
%FILE_MD5%	%FILE%
<!-- END_BLOCK UPDATE -->

[DELETE]
<!-- BEGIN_BLOCK DELETE -->
%FILE_MD5%	%FILE%
<!-- END_BLOCK DELETE -->

[DESCRIPTION]
%DESCRIPTION%