-- phpMyAdmin SQL Dump
-- version 4.2.12deb2+deb8u2
-- http://www.phpmyadmin.net
--
-- Client :  localhost
-- Généré le :  Ven 21 Avril 2017 à 20:56
-- Version du serveur :  5.5.54-0+deb8u1
-- Version de PHP :  5.6.30-0+deb8u1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données :  `MY-GRIMDAWN-GEAR`
--

--
-- Contenu de la table `ATTRIBUTES_NAMES`
--

INSERT INTO `ATTRIBUTES_NAMES` (`ID`, `LANG`, `TAG`, `GENDER`, `NAME`, `NAME_MD5`, `DESCRIPTION`, `DESCRIPTION_MD5`, `LAST_CHANGE`) VALUES
(1, 'en-EN', '', 'ms', '', '', '', '', '2017-04-17 06:17:45'),
(2, 'fr-FR', '', 'ms', '', '', '', '', '2017-04-17 06:17:49'),
(3, 'el-EL', '', 'ms', '', '', '', '', '2017-04-17 06:18:24'),
(4, 'es-ES', '', 'ms', '', '', '', '', '2017-04-17 06:18:34'),
(5, 'ja-JA', '', 'ms', '', '', '', '', '2017-04-17 06:18:43'),
(6, 'zh-ZH', '', 'ms', '', '', '', '', '2017-04-17 06:18:55'),
(7, 'pt-PT', '', 'ms', '', '', '', '', '2017-04-17 06:19:13'),
(8, 'ru-RU', '', 'ms', '', '', '', '', '2017-04-17 06:19:38'),
(9, 'de-DE', '', 'ms', '', '', '', '', '2017-04-17 06:20:00'),
(10, 'cs-CS', '', 'ms', '', '', '', '', '2017-04-17 06:20:20'),
(11, 'it-IT', '', 'ms', '', '', '', '', '2017-04-17 06:20:51'),
(12, 'vi-VI', '', 'ms', '', '', '', '', '2017-04-17 06:21:08'),
(13, 'pl-PL', '', 'ms', '', '', '', '', '2017-04-17 06:21:18'),
(14, 'bg-BG', '', 'ms', '', '', '', '', '2017-04-17 06:21:28');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
